package org.scalsys.idea_creation.model;

// Generated Jul 18, 2013 10:36:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgileIdea generated by hbm2java
 */
@Entity
@Table(name = "agile_idea", catalog = "agileinnovationtoolkitdb")
public class AgileIdea implements java.io.Serializable {

	private String ideaId;
	private String name;
	private String description;
	private Date inventedDate;
	private Date updatedDate;
	private boolean isDeleted;
	private Long inventorId;
	private String innoArena;
	private String descriptorFilePath;

	public AgileIdea() {
	}

	public AgileIdea(String ideaId, String name, Date inventedDate,
			Date updatedDate, boolean isDeleted) {
		this.ideaId = ideaId;
		this.name = name;
		this.inventedDate = inventedDate;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
	}

	public AgileIdea(String ideaId, String name, String description,
			Date inventedDate, Date updatedDate, boolean isDeleted,
			Long inventorId, String innoArena, String descriptorFilePath) {
		this.ideaId = ideaId;
		this.name = name;
		this.description = description;
		this.inventedDate = inventedDate;
		this.updatedDate = updatedDate;
		this.isDeleted = isDeleted;
		this.inventorId = inventorId;
		this.innoArena = innoArena;
		this.descriptorFilePath = descriptorFilePath;
	}

	@Id
	@Column(name = "idea_id", unique = true, nullable = false, length = 10)
	public String getIdeaId() {
		return this.ideaId;
	}

	public void setIdeaId(String ideaId) {
		this.ideaId = ideaId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "invented_date", nullable = false, length = 19)
	public Date getInventedDate() {
		return this.inventedDate;
	}

	public void setInventedDate(Date inventedDate) {
		this.inventedDate = inventedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "is_deleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "inventor_id")
	public Long getInventorId() {
		return this.inventorId;
	}

	public void setInventorId(Long inventorId) {
		this.inventorId = inventorId;
	}

	@Column(name = "inno_arena", length = 50)
	public String getInnoArena() {
		return this.innoArena;
	}

	public void setInnoArena(String innoArena) {
		this.innoArena = innoArena;
	}

	@Column(name = "descriptorFilePath", length = 50)
	public String getDescriptorFilePath() {
		return this.descriptorFilePath;
	}

	public void setDescriptorFilePath(String descriptorFilePath) {
		this.descriptorFilePath = descriptorFilePath;
	}

	@Override
	public String toString() {
		String newIdeaDetails = "\n" + super.toString() + "\nIdea Id : "
				+ getIdeaId() + "\nIdea Name : " + getName()
				+ "\nIdea Description : " + getDescription()
				+ "\nInnovation Arena : " + getInnoArena();
		return newIdeaDetails;
	}

}
