package org.scalsys.agile.model;
// default package
// Generated Jul 19, 2013 12:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdeaSubcatagory generated by hbm2java
 */
@Entity
@Table(name = "idea_subcatagory", catalog = "exo_platform_idm")
public class IdeaSubcatagory implements java.io.Serializable {

	private long subcatagoryId;
	private IdeaCatagory ideaCatagory;
	private String name;
	private Set ideas = new HashSet(0);

	public IdeaSubcatagory() {
	}

	public IdeaSubcatagory(long subcatagoryId, IdeaCatagory ideaCatagory,
			String name) {
		this.subcatagoryId = subcatagoryId;
		this.ideaCatagory = ideaCatagory;
		this.name = name;
	}

	public IdeaSubcatagory(long subcatagoryId, IdeaCatagory ideaCatagory,
			String name, Set ideas) {
		this.subcatagoryId = subcatagoryId;
		this.ideaCatagory = ideaCatagory;
		this.name = name;
		this.ideas = ideas;
	}

	@Id
	@Column(name = "subcatagory_id", unique = true, nullable = false)
	public long getSubcatagoryId() {
		return this.subcatagoryId;
	}

	public void setSubcatagoryId(long subcatagoryId) {
		this.subcatagoryId = subcatagoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catagory_id", nullable = false)
	public IdeaCatagory getIdeaCatagory() {
		return this.ideaCatagory;
	}

	public void setIdeaCatagory(IdeaCatagory ideaCatagory) {
		this.ideaCatagory = ideaCatagory;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ideaSubcatagory")
	public Set getIdeas() {
		return this.ideas;
	}

	public void setIdeas(Set ideas) {
		this.ideas = ideas;
	}

}
