package org.scalsys.agile.model;

// default package
// Generated Jul 19, 2013 12:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdeaCatagory generated by hbm2java
 */
@Entity
@Table(name = "idea_catagory", catalog = "exo_platform_idm")
public class IdeaCatagory implements java.io.Serializable {

	private long categoryId;
	private String categoryName;
	private Set ideas = new HashSet(0);
	private Set ideaSubcatagories = new HashSet(0);

	public IdeaCatagory() {
	}

	public IdeaCatagory(long categoryId, String categoryName) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
	}

	public IdeaCatagory(long categoryId, String categoryName, Set ideas,
			Set ideaSubcatagories) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.ideas = ideas;
		this.ideaSubcatagories = ideaSubcatagories;
	}

	@Id
	@Column(name = "category_id", unique = true, nullable = false)
	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category_name", nullable = false, length = 70)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ideaCatagory")
	public Set getIdeas() {
		return this.ideas;
	}

	public void setIdeas(Set ideas) {
		this.ideas = ideas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ideaCatagory")
	public Set getIdeaSubcatagories() {
		return this.ideaSubcatagories;
	}

	public void setIdeaSubcatagories(Set ideaSubcatagories) {
		this.ideaSubcatagories = ideaSubcatagories;
	}

}
