package org.scalsys.agile.model;
// default package
// Generated Jul 19, 2013 12:21:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IdeaDescriptorFile generated by hbm2java
 */
@Entity
@Table(name = "idea_descriptor_file", catalog = "exo_platform_idm")
public class IdeaDescriptorFile implements java.io.Serializable {

	private Long fileId;
	private Idea idea;
	private String fileName;

	public IdeaDescriptorFile() {
	}

	public IdeaDescriptorFile(Idea idea, String fileName) {
		this.idea = idea;
		this.fileName = fileName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "file_id", unique = true, nullable = false)
	public Long getFileId() {
		return this.fileId;
	}

	public void setFileId(Long fileId) {
		this.fileId = fileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idea_id", nullable = false)
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@Column(name = "file_name", nullable = false)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

}
