package org.scalsys.agile.model;
// default package
// Generated Jul 19, 2013 12:21:44 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdeaType generated by hbm2java
 */
@Entity
@Table(name = "idea_type", catalog = "exo_platform_idm")
public class IdeaType implements java.io.Serializable {

	private Long ideaTypeId;
	private String ideaTypeName;
	private Set ideas = new HashSet(0);

	public IdeaType() {
	}

	public IdeaType(String ideaTypeName) {
		this.ideaTypeName = ideaTypeName;
	}

	public IdeaType(String ideaTypeName, Set ideas) {
		this.ideaTypeName = ideaTypeName;
		this.ideas = ideas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idea_type_id", unique = true, nullable = false)
	public Long getIdeaTypeId() {
		return this.ideaTypeId;
	}

	public void setIdeaTypeId(Long ideaTypeId) {
		this.ideaTypeId = ideaTypeId;
	}

	@Column(name = "idea_type_name", nullable = false, length = 100)
	public String getIdeaTypeName() {
		return this.ideaTypeName;
	}

	public void setIdeaTypeName(String ideaTypeName) {
		this.ideaTypeName = ideaTypeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ideaType")
	public Set getIdeas() {
		return this.ideas;
	}

	public void setIdeas(Set ideas) {
		this.ideas = ideas;
	}

}
