package org.scalsys.agile.model;

// default package
// Generated Jul 19, 2013 12:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IdeaVote generated by hbm2java
 */
@Entity
@Table(name = "idea_vote", catalog = "exo_platform_idm")
public class IdeaVote implements java.io.Serializable {

	private long voteId;
	private Date startVoting;
	private Date endVoting;
	private Set ideas = new HashSet(0);

	public IdeaVote() {
	}

	public IdeaVote(long voteId, Date startVoting) {
		this.voteId = voteId;
		this.startVoting = startVoting;
	}

	public IdeaVote(long voteId, Date startVoting, Date endVoting, Set ideas) {
		this.voteId = voteId;
		this.startVoting = startVoting;
		this.endVoting = endVoting;
		this.ideas = ideas;
	}

	@Id
	@Column(name = "vote_id", unique = true, nullable = false)
	public long getVoteId() {
		return this.voteId;
	}

	public void setVoteId(long voteId) {
		this.voteId = voteId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_voting", nullable = false, length = 19)
	public Date getStartVoting() {
		return this.startVoting;
	}

	public void setStartVoting(Date startVoting) {
		this.startVoting = startVoting;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_voting", length = 19)
	public Date getEndVoting() {
		return this.endVoting;
	}

	public void setEndVoting(Date endVoting) {
		this.endVoting = endVoting;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ideaVote")
	public Set getIdeas() {
		return this.ideas;
	}

	public void setIdeas(Set ideas) {
		this.ideas = ideas;
	}

}
